### ISSUE TITLE
Setup localhost for backend

### ISSUE THREAD

**Issue by Env-byte** [CtrlPlusAltPlusDefeat/backend#3]
### steps
- We need to configure a docker network `docker network create local-api-network`
- We then need to create the DynamoDB container
```
docker run -d -p 8000:8000 --network=local-api-network --name dynamo-local amazon/dynamodb-local
```
To confirm that it’s running we can run: `aws dynamodb list-tables --endpoint-url http://localhost:8000/`
- We then need to connect `aws-sam` to the network using this command: `sam local start-api --docker-network local-api-network
`
- Then we can create a `aws-sam` template file :
```
AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Resources:
  LambdaGet:
    Type: AWS::Serverless::Function
    Properties:
      Handler: dist/Api/Handler.handler
      Runtime: nodejs18.x
      Timeout: 15
      Events:
        Http:
          Type: Api
          Properties:
            Path: /{proxy+}
            Method: ANY

```

### Resources
- [How to run API Gateway, AWS Lambda and DynamoDB locally](https://www.google.com/search?q=run+api+gateway+and+dynamodb+locally&oq=run+apigateway+and+dynamodb+loc&aqs=chrome.1.69i57j33i10i160l3.10413j0j7&sourceid=chrome&ie=UTF-8)
- [Using DynamoDB locally](https://stackoverflow.com/questions/48342912/how-to-use-dynamodb-locally-with-lambda)
